### ISSUE TITLE
Line endings in index.js

### ISSUE THREAD

**Issue by bodograumann** [David-Desmaisons/vue-cli-plugin-component#2]
I think it is common practice to use unix line-endings.
The generated index.js file has dos line endings though.

**Comment by David-Desmaisons** [comment]
Well I only have a windows machine.
Even if I accept a PR with this change, they will be lost when I will update this file.
So I will not provide this change.

**Comment by Garito** [comment]
You should use the linter
Will avoid this issue or this one https://github.com/David-Desmaisons/vue-cli-plugin-component/blob/c1c2313bd1d8684e6e88f9ff334aabaf270d4530/generator/template/src/index.js#L1 (the ; at the end of the line) or a double quotes I don't remember where they are (I'll post it here when I find them)

**Comment by David-Desmaisons** [comment]
Will provide linting after updating files if the project has a lint configuration.

**Comment by Garito** [comment]
Yeah, depending on how the linter is configured will raise some warnings
Nowadays a linter is a polite thing to use IMO

**Comment by bodograumann** [comment]
You can actually let git handle this problem for you. See `core.autocrlf` in the [git book](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration) or the [github docs](https://help.github.com/articles/dealing-with-line-endings/). Which options you need to choose exactly depends on your specific setup of course.
