### ISSUE TITLE
This dependency was not found when using typescript

### ISSUE THREAD

**Issue by HamedFathi** [David-Desmaisons/vue-cli-plugin-component#4]
I created a very very simple component like the following:

![screenshot_1](https://user-images.githubusercontent.com/8418700/49700062-f5d58700-fbee-11e8-8735-acf629d9e12d.png)
![screenshot_2](https://user-images.githubusercontent.com/8418700/49700063-f66e1d80-fbee-11e8-9074-3479af062330.png)
![screenshot_3](https://user-images.githubusercontent.com/8418700/49700064-f706b400-fbee-11e8-81b3-c54fa3b74b48.png)

The component compiled successfully.

![screenshot_4](https://user-images.githubusercontent.com/8418700/49700084-54026a00-fbef-11e8-9667-051c863c7c06.png)

Based on your `Read Me` you said:

> Use serve to serve the application example in the example folder
> npm run serve

I ran the command in `example` folder but I got an error

![screenshot_5](https://user-images.githubusercontent.com/8418700/49700137-22d66980-fbf0-11e8-905b-69232839ed10.png)

However, The following tip does not work for me. I ran it in the main directory and example folder.

``` To install it, you can run: npm install --save ...\vue-component\example\main.js ```    

I prefer to use `Typescript` so I hope this is not about that! You can find the sample in [here](https://github.com/HamedFathi/Vue-Component)

What should I do? please guide me to use your awesome plugin.

**Comment by David-Desmaisons** [comment]
Edit package.JSON:

Change:
`serve: "vue-cli-service serve ./example/main.js --open",
`
Into:
`serve: "vue-cli-service serve ./example/main.ts --open",
`

And
`build: `vue-cli-service build --name ${packageName} --entry ./src/index.js --target lib`,`

Into:
`build: `vue-cli-service build --name ${packageName} --entry ./src/index.ts --target lib`,`

**Comment by David-Desmaisons** [comment]
This is a temporaray bypass I will work to try to include a fix  in next version.

**Comment by HamedFathi** [comment]
Thanks for your quick answer.

It works but needs some other changes too as the following:

1. Convert `.js` extension to `.ts` for 
```${packageName}\src\index.js```

2. Update `tsconfig.json` for your new `example` folder.
```
"include": [
"example/**/*.ts",
"example/**/*.tsx",
"example/**/*.vue"
]
```

I am waiting for your vNext plugin system with fully Typescript support.

**Comment by David-Desmaisons** [comment]
Thanks for the additional info! It will be helpfull when working on the fix.

**Comment by David-Desmaisons** [comment]
@HamedFathi  I am not sure about including the example in the npm register.  
I think adding "uncompiled" js, ts and vue files from src folder would be a good idea thoutgh.

**Comment by HamedFathi** [comment]
@David-Desmaisons 

Seems cool, Did you update it? I could not find your new changes.

**Comment by David-Desmaisons** [comment]
I just published it. Version 1.9.1
