### ISSUE TITLE
Please support dash (-) for component name

### ISSUE THREAD

**Issue by HamedFathi** [David-Desmaisons/vue-cli-plugin-component#5]
Most of the time Vue components start with `v-` or anything like this.

Your plugin system has some problems with the dash (-).

![screenshot_1](https://user-images.githubusercontent.com/8418700/49701005-8e720400-fbfb-11e8-8161-04d9f64477d7.png)

As you can see I wrote `v-hello` as a component name.
The following picture shows a problem in compilation
![screenshot_2](https://user-images.githubusercontent.com/8418700/49701060-443d5280-fbfc-11e8-9e4b-f05e3cb41438.png)

I am not sure exists any better way or not but you can use a dash (-) free name for `import` components.

![screenshot_4](https://user-images.githubusercontent.com/8418700/49701029-de50cb00-fbfb-11e8-844d-5aaade130b3b.png)

However, writing a `name : value` object for all components in not cool!
```
components: {
    'v-hello': vhello
  }
```

**Comment by David-Desmaisons** [comment]
VHello would work and be transformed in v-hello by the plugin in the templates..

**Comment by HamedFathi** [comment]
Good answer, enough for me :)
