### ISSUE TITLE
Add component plugin on top of Vuetify plugin

### ISSUE THREAD

**Issue by HamedFathi** [David-Desmaisons/vue-cli-plugin-component#6]
Hi

I am not sure, It is a problem of your plugin system. I need your help to figure out a solution.
I created a very simple Vue CLI project and I installed Vuetify on top of it. `vue add vuetify`.
After that I ran the `vue add component` command on it.

![image](https://user-images.githubusercontent.com/8418700/49725860-fc610e80-fc81-11e8-9f1f-e7a18253ecf2.png)

Everything compile successfully but the application does not work perfectly. Without the plugin system Vuetify and all of the controls works perfectly.

![image](https://user-images.githubusercontent.com/8418700/49726152-93c66180-fc82-11e8-8a24-aa41d511f2f8.png)

![image](https://user-images.githubusercontent.com/8418700/49726216-b8bad480-fc82-11e8-982f-2790b696ff46.png)

You can find the repository [here](https://github.com/HamedFathi/Vuetify-Component).

I need Vuetify to write some components based on it.

Any idea?

**Comment by David-Desmaisons** [comment]
Any message on the console?
That said if I were you, I would add vuetify manually after create the component with the plugin, since it would not be a great deal of work and give you much more control.

**Comment by David-Desmaisons** [comment]
@HamedFathi  Try version 1.9.1 as you are using ts. Please take a look also at my comments above.

**Comment by HamedFathi** [comment]
@David-Desmaisons  

Thanks, I will check this.

However, I found the problem I should use `v-app` for activating Vuetify colors so I close this.


![tip](https://user-images.githubusercontent.com/16421948/41846248-7580b27c-78b9-11e8-879b-9ccf82d6eb18.png)
