### ISSUE TITLE
Question about creating a new package

### ISSUE THREAD

**Issue by scottadamsmith** [David-Desmaisons/vue-cli-plugin-component#7]
The documentation cites what to do when installing in an existing project, but I am not seeing anything regarding starting from scratch. Perhaps I am just seeing it? Is the expectation that we initialize our project using `vue create` and then afterward us `vue add component`? Or is there a way to use this to initialize the project right out of the gate?

**Comment by David-Desmaisons** [comment]
`vue create`  + `vue add component` will work without restriction.
