### ISSUE TITLE
[Question] How to publish a plugin?

### ISSUE THREAD

**Issue by HamedFathi** [David-Desmaisons/vue-cli-plugin-component#8]
Hello, This issue is just a question.
I wrote a plugin on [voca.js](https://vocajs.com). you can find it [here](https://github.com/HamedFathi/VueVoca).It is based on your great plugin system.
I use two commands `yarn build` and `npm pack` to create a npm package but It does not work on this way however in works perfectly in `example` section. Can you help me to figre out the problem? Should I do more to resolve this to publish correct npm package?

**Comment by David-Desmaisons** [comment]
I am not sure I undersatnd what the problem is. Did you try to add "npm build && npm pack" to the prepublishOnly script?

**Comment by HamedFathi** [comment]
Yes, Let me explain more

**index.ts**
```js
import VueVoca from './vue-voca';
export {
    VueVoca
};
```

**vue-voca.ts**
```js
import vue from 'vue';

export default {
  install(Vue: typeof vue) {
    Vue.prototype.$voca = require('voca');
  }
};
```

**vue.d.ts**
```js
import Vue from 'vue';
import vc from 'voca';
declare module 'vue/types/vue' {
  export interface Vue {
    $voca: vc.VocaStatic;
  }
}
```
To create npm package I use this command

`vue-cli-service build --name vue-voca --entry ./src/index.ts --target lib`
and `npm pack`.

**package.json**
```js
{
  "name": "vue-voca",
  "version": "1.0.0",
  "private": false,
  "scripts": {
    "serve": "vue-cli-service serve ./example/main.ts --open",
    "build": "vue-cli-service build --name vue-voca --entry ./src/index.ts --target lib",
    "prepublishOnly": "npm run build"
  },
  "dependencies": {
    "@types/voca": "^1.4.0",
    "voca": "^1.4.0",
    "vue": "^2.6.7"
  },
  "devDependencies": {
    "@vue/cli-plugin-typescript": "^3.4.1",
    "@vue/cli-service": "^3.4.1",
    "fibers": "^3.1.1",
    "sass": "^1.17.2",
    "sass-loader": "^7.1.0",
    "typescript": "^3.3.3333",
    "vue-cli-plugin-component": "^1.10.5",
    "vue-template-compiler": "^2.6.7"
  },
  "files": [
    "dist/*.css",
    "dist/*.map",
    "dist/*.js",
    "src/*"
  ],
  "keywords": [
    "vue",
    "component"
  ],
  "types": "src/vue.d.ts",
  "typings": "src/vue.d.ts",
  "main": "dist/vue-services.umd.js",
  "module": "dist/vue-services.common.js"
}
```
**tsconfig**

```js
{
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "declaration": true,  
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

But after using the npm package in another project `yarn add localaddress` I got an error. VueVoca does not recognize and Typescript can not work with it well.

[![enter image description here][1]][1]

[![enter image description here][2]][2]

[![enter image description here][3]][3]

[![enter image description here][4]][4]

``` 
    webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Error in render: "TypeError: Cannot read property 'swapCase' of undefined"
    
    found in
   
---> <HelloWorld> at src/components/HelloWorld.vue
            <App> at src/App.vue
                 <Root>
```


  [1]: https://i.stack.imgur.com/66Zw1.png
  [2]: https://i.stack.imgur.com/G8EKl.png
  [3]: https://i.stack.imgur.com/b72Hz.png
  [4]: https://i.stack.imgur.com/st0Va.png

**Comment by David-Desmaisons** [comment]
Try:
```
import { Vuevoca} from "vue-voca";
```

instead of 

```
import * as  Vuevoca from "vue-voca";
```

**Comment by HamedFathi** [comment]
No, I had tested this before :(

**Comment by David-Desmaisons** [comment]
I mean the example you shared uses:

```
import * as  Vuevoca from "vue-voca";
```
This won't work because it is exported as  { Vuevoca}. If there is a problem with the import { Vuevoca} from "vue-voca"; then you should share the coresspoonding scrrenshots.

**Comment by HamedFathi** [comment]
The screenshot:

![image](https://user-images.githubusercontent.com/8418700/53593127-1dfcd280-3bad-11e9-9eeb-5a0a819ec924.png)

```
Failed to compile.

./src/main.ts
Module not found: Error: Can't resolve 'vue-voca' in 'C:\...\vocatest\vocatest\src'
```

Really weird, I do not know how to write a simple plugin by Typescript in Vue with full intelisense support!

**Comment by David-Desmaisons** [comment]
Waht is the scenario to get this error, I am geeting confused.

**Comment by HamedFathi** [comment]
I am so sorry, May I ask you to download the source code [here](https://github.com/HamedFathi/VueVoca) on your system?

1. Create a NPM package on your local machine.
I use these commands: `yarn build` and `npm pack`

2. Create a new empty Vue project for testing purpose.
3. Install the local NPM package that you created in step 1.
I use this `yarn add local-package-addresss`

4. Use it like other plugins.
5. You will get an error.

Seems the package has a problem on user side not in development mode.

**Comment by HamedFathi** [comment]
Thanks I found the problem :)
